apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/kevinstl/lightning-kube-btcctl:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/kevinstl/lightning-kube-btcctl:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: lightning-kube-btcctl
        chartPath: charts/lightning-kube-btcctl
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/kevinstl/lightning-kube-btcctl"
          image.tag: "{{.DIGEST_HEX}}"
