kind: PersistentVolume
apiVersion: v1
metadata:
  name: lightning-shared
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/shared/"
